In [2]:
import numpy as np
print(np.__version__)

1.22.3


In [3]:
a = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(np.array(a))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
np.array(np.arange(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[ 1: :2]

## solution
arr[arr % 2 == 1]

# 여기서 arr % 2 == 1 은 조건부

array([1, 3, 5, 7, 9])

In [30]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[ arr % 2 == 1 ] = -1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [39]:
a = np.arange(10)

a.shape

a.reshape([2,5])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [47]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(a)
print(b)

np.vstack([a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

print(a)
print(b)

np.hstack([a,b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [63]:
a = np.array([1, 2, 3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

b = a[:]
print(b)
c = np.concatenate([np.repeat(a, 3),np.tile(a, 3)])

c


# 사용된 함수
# np.repeat : 각 인덱스를 반복
# np.tile : 전체를 반복
# np.concatenate : ndarray 합치기

#solution
#np.r_[np.repeat(a, 3), np.tile(a, 3)]

[1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [67]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#> array([2, 4])

np.intersect1d(a, b)

# 사용된 함수
# intersect1d(a,b) : 두 (a, b) ndarray 간의 공통 index 찾아서 출력


array([2, 4])

In [68]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a, b)

# 사용된 함수
# setdiff1d(a, b) : a 에서 두 ndarray 간의 공통 index를 지우고 출력

array([1, 2, 3, 4])